/* ============================================================
   Banco de preguntas de respaldo.
   El juego usa, en este orden:
     1. datos/preguntas.xlsx (si el juego corre desde la Raspberry)
     2. un Excel importado desde el menú
     3. este archivo
   Formato: [ "Pista", "RESPUESTA", "TIPO" ]
   - La respuesta es UNA palabra (o un número).
   - TIPO:
       CANCION  → "Completa el título de la canción" (la pista lleva ___)
       DISCO    → "Completa el nombre del disco"     (la pista lleva ___)
       PREGUNTA → una pregunta normal. Si lleva ___, se completa la frase;
                  si no, en pantalla dice "Responde con una palabra".
   - Escribe la pista como se diría en voz alta, en mayúsculas y minúsculas.
   - Sin letras de canciones: títulos, discos, nombres, lugares y datos.
   Verificar los datos antes de cada fecha.
   ============================================================ */
window.PREGUNTAS = {
  "MAROON 5": [
    ["Moves Like ___", "JAGGER", "CANCION"],
    ["One More ___", "NIGHT", "CANCION"],
    ["Girls Like ___", "YOU", "CANCION"],
    ["She Will Be ___", "LOVED", "CANCION"],
    ["This ___", "LOVE", "CANCION"],
    ["Sunday ___", "MORNING", "CANCION"],
    ["Harder to ___", "BREATHE", "CANCION"],
    ["Makes Me ___", "WONDER", "CANCION"],
    ["Wake Up ___", "CALL", "CANCION"],
    ["Won't Go Home ___ You", "WITHOUT", "CANCION"],
    ["What Lovers ___", "DO", "CANCION"],
    ["Beautiful ___", "MISTAKES", "CANCION"],
    ["Love ___", "SOMEBODY", "CANCION"],
    ["Don't ___ Know", "WANNA", "CANCION"],
    ["Give a Little ___", "MORE", "CANCION"],
    ["If I Never See Your ___ Again", "FACE", "CANCION"],
    ["Nobody's ___", "LOVE", "CANCION"],
    ["Lucky ___", "STRIKE", "CANCION"],
    ["Songs About ___", "JANE", "DISCO"],
    ["It Won't Be ___ Before Long", "SOON", "DISCO"],
    ["Hands All ___", "OVER", "DISCO"],
    ["Red Pill ___", "BLUES", "DISCO"],
    ["¿Cómo se apellida Adam, el vocalista de Maroon 5?", "LEVINE", "PREGUNTA"],
    ["¿Qué instrumento toca Adam Levine además de cantar?", "GUITARRA", "PREGUNTA"],
    ["Antes de llamarse Maroon 5, la banda se llamaba Kara's ___", "FLOWERS", "PREGUNTA"],
    ["Maroon 5 se formó en la ciudad de Los ___, California", "ÁNGELES", "PREGUNTA"],
    ["¿Qué canción de Maroon 5 grabaron con Wiz Khalifa?", "PAYPHONE", "PREGUNTA"],
    ["¿Qué canción de Maroon 5 grabaron con el rapero Future?", "COLD", "PREGUNTA"],
    ["¿En el video de qué canción la banda llega de sorpresa a varias bodas?", "SUGAR", "PREGUNTA"],
    ["¿Qué canción de 2019 es un brindis por los seres queridos que ya no están?", "MEMORIES", "PREGUNTA"],
    ["¿Qué éxito de 2014 se titula «mapas» en inglés?", "MAPS", "PREGUNTA"],
    ["¿Qué éxito de 2014 se titula «animales» en inglés?", "ANIMALS", "PREGUNTA"],
    ["¿Qué canción de 2010 se titula «miseria» en inglés?", "MISERY", "PREGUNTA"],
    ["¿Qué canción de 2012 se titula «luz del día» en inglés?", "DAYLIGHT", "PREGUNTA"],
    ["Adam Levine fue coach durante años del programa de talentos The ___", "VOICE", "PREGUNTA"],
    ["En 2019 Maroon 5 encabezó el show de medio tiempo del Super ___", "BOWL", "PREGUNTA"],
    ["Su disco de 2021 lleva el apodo de su mánager fallecido, Jordan Feldstein: ___", "JORDI", "PREGUNTA"]
  ],

  "ALEJANDRO SANZ": [
    ["Corazón ___", "PARTÍO", "CANCION"],
    ["Amiga ___", "MÍA", "CANCION"],
    ["Y si fuera ___", "ELLA", "CANCION"],
    ["Mi soledad y ___", "YO", "CANCION"],
    ["Cuando nadie me ___", "VE", "CANCION"],
    ["Pisando ___", "FUERTE", "CANCION"],
    ["Los dos cogidos de la ___", "MANO", "CANCION"],
    ["Deja que te ___", "BESE", "CANCION"],
    ["Hoy llueve, hoy ___", "DUELE", "CANCION"],
    ["No me ___", "COMPARES", "CANCION"],
    ["Mi persona ___", "FAVORITA", "CANCION"],
    ["Looking for ___", "PARADISE", "CANCION"],
    ["Siempre es de ___", "NOCHE", "CANCION"],
    ["Quisiera ___", "SER", "CANCION"],
    ["Desde ___", "CUÁNDO", "CANCION"],
    ["Si hay ___", "DIOS", "CANCION"],
    ["Te lo agradezco, pero ___", "NO", "CANCION"],
    ["El alma al ___", "AIRE", "DISCO"],
    ["No es lo ___", "MISMO", "DISCO"],
    ["Viviendo ___", "DEPRISA", "DISCO"],
    ["El tren de los ___", "MOMENTOS", "DISCO"],
    ["La música no se ___", "TOCA", "DISCO"],
    ["Paraíso ___", "EXPRESS", "DISCO"],
    ["Si tú me ___", "MIRAS", "DISCO"],
    ["¿Cómo se llama su disco de 1997, el de «Corazón partío»?", "MÁS", "PREGUNTA"],
    ["Su disco de 2015 se llama como un jarabe dulce: ___", "SIROPE", "PREGUNTA"],
    ["Su disco de 2019 tiene nombre de hashtag: #El___", "DISCO", "PREGUNTA"],
    ["Su disco de 2021 lleva su apellido artístico: ___", "SANZ", "PREGUNTA"],
    ["La canción que grabó con Shakira en 2005 se llama La ___", "TORTURA", "PREGUNTA"],
    ["«Mi persona favorita» la grabó con la cantante Camila ___", "CABELLO", "PREGUNTA"],
    ["«Looking for Paradise» la grabó con la cantante Alicia ___", "KEYS", "PREGUNTA"],
    ["«Deja que te bese» la grabó con el cantante Marc ___", "ANTHONY", "PREGUNTA"],
    ["¿En qué ciudad nació Alejandro Sanz?", "MADRID", "PREGUNTA"],
    ["¿De qué país es Alejandro Sanz?", "ESPAÑA", "PREGUNTA"],
    ["¿Qué género musical andaluz se escucha en muchas de sus canciones?", "FLAMENCO", "PREGUNTA"],
    ["Su nombre real es Alejandro Sánchez ___", "PIZARRO", "PREGUNTA"]
  ],

  "INTOCABLE": [
    ["¿Y todo para ___?", "QUÉ", "CANCION"],
    ["Enséñame a ___", "OLVIDAR", "CANCION"],
    ["Alguien te va a hacer ___", "LLORAR", "CANCION"],
    ["¿Dónde ___?", "ESTÁS", "CANCION"],
    ["Fuerte no ___", "SOY", "CANCION"],
    ["Nuestro destino estaba ___", "ESCRITO", "DISCO"],
    ["¿Cómo se apellida Ricky, el vocalista y acordeonista de Intocable?", "MUÑOZ", "PREGUNTA"],
    ["¿Qué instrumento toca Ricky Muñoz mientras canta?", "ACORDEÓN", "PREGUNTA"],
    ["¿De qué estado de Estados Unidos es Intocable?", "TEXAS", "PREGUNTA"],
    ["¿En qué pueblo de Texas nació Intocable?", "ZAPATA", "PREGUNTA"],
    ["La guitarra de doce cuerdas típica del norteño se llama bajo ___", "SEXTO", "PREGUNTA"],
    ["¿Cómo se llama la música de los mexicanos de Texas que toca Intocable?", "TEJANO", "PREGUNTA"]
  ],

  // Se mezcla con Intocable (ver config.js).
  "NORTEÑO": [
    ["Al acordeonista Ramón Ayala le dicen el Rey del ___", "ACORDEÓN", "PREGUNTA"],
    ["«Tragos amargos» es un clásico de Ramón ___", "AYALA", "PREGUNTA"],
    ["«La puerta negra» es de Los Tigres del ___", "NORTE", "PREGUNTA"],
    ["«Contrabando y traición» es de Los Tigres del ___", "NORTE", "PREGUNTA"],
    ["«Me caí de la nube» es un clásico de Cornelio ___", "REYNA", "PREGUNTA"],
    ["«Laurita Garza» es de Los Invasores de Nuevo ___", "LEÓN", "PREGUNTA"],
    ["Ramón Ayala y Cornelio Reyna formaron Los Relámpagos del ___", "NORTE", "PREGUNTA"],
    ["¿Cómo le dicen a Selena? La reina del Tex-___", "MEX", "PREGUNTA"],
    ["¿Qué baile europeo, de ritmo rápido, está en las raíces del norteño?", "POLKA", "PREGUNTA"],
    ["¿De qué ciudad es el grupo norteño Pesado?", "MONTERREY", "PREGUNTA"]
  ],

  "ROD STEWART": [
    ["Da Ya Think I'm ___?", "SEXY", "CANCION"],
    ["Maggie ___", "MAY", "CANCION"],
    ["Young ___", "TURKS", "CANCION"],
    ["Have I Told You ___", "LATELY", "CANCION"],
    ["Forever ___", "YOUNG", "CANCION"],
    ["Some Guys Have All the ___", "LUCK", "CANCION"],
    ["Hot ___", "LEGS", "CANCION"],
    ["Tonight's the ___", "NIGHT", "CANCION"],
    ["Baby ___", "JANE", "CANCION"],
    ["Downtown ___", "TRAIN", "CANCION"],
    ["Rhythm of My ___", "HEART", "CANCION"],
    ["The First ___ Is the Deepest", "CUT", "CANCION"],
    ["You Wear It ___", "WELL", "CANCION"],
    ["I Don't Want to Talk About ___", "IT", "CANCION"],
    ["Reason to ___", "BELIEVE", "CANCION"],
    ["All for ___", "LOVE", "CANCION"],
    ["Every Picture Tells a ___", "STORY", "DISCO"],
    ["Atlantic ___", "CROSSING", "DISCO"],
    ["Blondes Have More ___", "FUN", "DISCO"],
    ["A Night on the ___", "TOWN", "DISCO"],
    ["Gasoline ___", "ALLEY", "DISCO"],
    ["¿Qué canción de 1975 habla de navegar por el mar?", "SAILING", "PREGUNTA"],
    ["Antes de ser solista, cantó en la banda The ___", "FACES", "PREGUNTA"],
    ["Su primer grupo famoso lo formó con el guitarrista Jeff ___", "BECK", "PREGUNTA"],
    ["En los años 60 lo apodaban «Rod the ___»", "MOD", "PREGUNTA"],
    ["¿En qué ciudad nació Rod Stewart?", "LONDRES", "PREGUNTA"],
    ["¿De qué país es su familia paterna, al que siempre dice pertenecer?", "ESCOCIA", "PREGUNTA"],
    ["¿De qué equipo de futbol escocés es fanático Rod Stewart?", "CELTIC", "PREGUNTA"],
    ["Su serie de discos de clásicos se llama The Great American ___", "SONGBOOK", "PREGUNTA"],
    ["Desde que lo nombraron caballero en 2016 le dicen ___ Rod Stewart", "SIR", "PREGUNTA"],
    ["«All for Love» la grabó con Bryan Adams y ___", "STING", "PREGUNTA"],
    ["¿En qué playa de Río de Janeiro dio un concierto histórico en 1994?", "COPACABANA", "PREGUNTA"],
    ["Su gran pasatiempo es armar maquetas gigantes de ___", "TRENES", "PREGUNTA"]
  ],

  "ANUEL AA": [
    ["Ella quiere ___", "BEBER", "CANCION"],
    ["Hasta que Dios ___", "DIGA", "CANCION"],
    ["Mejor que ___", "YO", "CANCION"],
    ["Las leyendas nunca ___", "MUEREN", "DISCO"],
    ["Su disco con Ozuna se llama Los ___", "DIOSES", "PREGUNTA"],
    ["¿Cómo se llama su disco de 2020, que lleva su primer nombre?", "EMMANUEL", "PREGUNTA"],
    ["Su nombre real es Emmanuel ___ Santiago", "GAZMEY", "PREGUNTA"],
    ["Anuel AA nació en Carolina, Puerto ___", "RICO", "PREGUNTA"],
    ["¿Con qué cantante puertorriqueño grabó el disco «Los Dioses»?", "OZUNA", "PREGUNTA"],
    ["¿Qué canción de 2019 grabó con Karol G?", "SECRETO", "PREGUNTA"],
    ["¿Qué canción de 2019 junta a Anuel con Daddy Yankee, Karol G, Ozuna y J Balvin?", "CHINA", "PREGUNTA"],
    ["¿Qué canción grabó con Tekashi 6ix9ine en 2018?", "BEBÉ", "PREGUNTA"],
    ["¿Cómo se llama su primer gran éxito, de 2016?", "SOLA", "PREGUNTA"],
    ["El remix de «Sola» lo grabó con Daddy Yankee, Wisin, Farruko y Zion & ___", "LENNOX", "PREGUNTA"],
    ["«Adicto» la grabó con Ozuna y el productor ___", "TAINY", "PREGUNTA"],
    ["«Hasta que Dios diga» la grabó con Bad ___", "BUNNY", "PREGUNTA"],
    ["Además del reguetón, su género es el ___ latino", "TRAP", "PREGUNTA"]
  ],

  "TIGRES": [
    ["¿Cómo se llama el estadio de Tigres? Estadio ___", "UNIVERSITARIO", "PREGUNTA"],
    ["¿Cómo le dicen al Estadio Universitario por lo caliente de su ambiente?", "VOLCÁN", "PREGUNTA"],
    ["El Volcán está en el municipio de San Nicolás de los ___", "GARZA", "PREGUNTA"],
    ["Tigres es el equipo de la Universidad Autónoma de Nuevo ___", "LEÓN", "PREGUNTA"],
    ["¿En qué año se fundó Tigres?", "1960", "PREGUNTA"],
    ["Los colores de Tigres son el azul y el ___", "AMARILLO", "PREGUNTA"],
    ["Por su uniforme amarillo y azul, a Tigres también le dicen los ___", "AURIAZULES", "PREGUNTA"],
    ["¿Qué animal es el emblema de la UANL?", "TIGRE", "PREGUNTA"],
    ["¿Cómo se apellida André-Pierre, el máximo goleador en la historia de Tigres?", "GIGNAC", "PREGUNTA"],
    ["¿De qué país es André-Pierre Gignac?", "FRANCIA", "PREGUNTA"],
    ["Con el técnico Ricardo «Tuca» ___, Tigres ganó cinco títulos de liga", "FERRETTI", "PREGUNTA"],
    ["¿De qué país es el técnico Ricardo «Tuca» Ferretti?", "BRASIL", "PREGUNTA"],
    ["Al portero argentino Nahuel Guzmán le apodan «El ___»", "PATÓN", "PREGUNTA"],
    ["El mediocampista argentino que fue capitán de Tigres: Guido ___", "PIZARRO", "PREGUNTA"],
    ["En 2020 Tigres ganó la Concacaf ___ League", "CHAMPIONS", "PREGUNTA"],
    ["En la final del Mundial de Clubes 2020, Tigres enfrentó al Bayern ___", "MÚNICH", "PREGUNTA"],
    ["A la afición de Tigres se le conoce como «La afición ___»", "INCOMPARABLE", "PREGUNTA"],
    ["La barra de Tigres se llama Libres y ___", "LOKOS", "PREGUNTA"],
    ["El partido entre Tigres y Rayados se llama el Clásico ___", "REGIO", "PREGUNTA"],
    ["¿Cómo se llama el equipo de mujeres de la UANL? Tigres ___", "FEMENIL", "PREGUNTA"]
  ],

  "RAYADOS": [
    ["¿Cómo se llama el estadio de Rayados? Estadio ___", "BBVA", "PREGUNTA"],
    ["Al Estadio BBVA le dicen el Gigante de ___", "ACERO", "PREGUNTA"],
    ["¿En qué año se inauguró el Estadio BBVA?", "2015", "PREGUNTA"],
    ["¿En qué municipio está el Estadio BBVA?", "GUADALUPE", "PREGUNTA"],
    ["El Estadio BBVA está junto al parque ecológico La ___", "PASTORA", "PREGUNTA"],
    ["Desde las gradas del BBVA se ve el Cerro de la ___", "SILLA", "PREGUNTA"],
    ["Antes del BBVA, Rayados jugaba de local en el Estadio ___", "TECNOLÓGICO", "PREGUNTA"],
    ["El nombre oficial de Rayados es Club de Futbol ___", "MONTERREY", "PREGUNTA"],
    ["¿En qué año se fundó Rayados?", "1945", "PREGUNTA"],
    ["El uniforme de Rayados tiene rayas verticales azules y ___", "BLANCAS", "PREGUNTA"],
    ["Además de Rayados, al equipo también le dicen La ___", "PANDILLA", "PREGUNTA"],
    ["¿En qué año ganó Rayados su primer título de liga?", "1986", "PREGUNTA"],
    ["Entre 2011 y 2013, ¿cuántas Concachampions seguidas ganó Rayados?", "TRES", "PREGUNTA"],
    ["Al técnico Víctor Manuel Vucetich le dicen el Rey ___", "MIDAS", "PREGUNTA"],
    ["Al delantero chileno Humberto Suazo le decían «___»", "CHUPETE", "PREGUNTA"],
    ["El máximo goleador en la historia de Rayados es Rogelio Funes ___", "MORI", "PREGUNTA"],
    ["Al ídolo regiomontano Jesús Arellano le decían «El ___»", "CABRITO", "PREGUNTA"],
    ["En 2025 llegó a Rayados el famoso defensa español Sergio ___", "RAMOS", "PREGUNTA"],
    ["Rayados quedó en tercer lugar del Mundial de ___ en 2012 y en 2019", "CLUBES", "PREGUNTA"],
    ["A la barra de Rayados se le conoce como La ___", "ADICCIÓN", "PREGUNTA"],
    ["El partido entre Rayados y Tigres se llama el Clásico ___", "REGIO", "PREGUNTA"],
    ["Monterrey es la capital del estado de Nuevo ___", "LEÓN", "PREGUNTA"]
  ],

  "BORREGOS": [
    ["El equipo del Tec de Monterrey se llama Borregos ___", "SALVAJES", "PREGUNTA"],
    ["Los Borregos juegan futbol ___", "AMERICANO", "PREGUNTA"],
    ["Borregos es el equipo del Tecnológico de ___", "MONTERREY", "PREGUNTA"],
    ["El Tec de Monterrey lo fundó el empresario Eugenio Garza ___", "SADA", "PREGUNTA"],
    ["¿En qué año se fundó el Tec de Monterrey?", "1943", "PREGUNTA"],
    ["Los colores de Borregos son el azul y el ___", "BLANCO", "PREGUNTA"],
    ["¿En qué año se inauguró el Estadio Borregos?", "2019", "PREGUNTA"],
    ["El Estadio Borregos se construyó en el lugar del antiguo Estadio ___", "TECNOLÓGICO", "PREGUNTA"],
    ["¿Qué equipo de futbol soccer jugó en el Estadio Tecnológico hasta 2015?", "RAYADOS", "PREGUNTA"],
    ["¿Cómo se llama la liga universitaria de futbol americano donde juega Borregos?", "ONEFA", "PREGUNTA"],
    ["El gran rival universitario de Borregos son los Auténticos ___", "TIGRES", "PREGUNTA"],
    ["El legendario coach de Borregos Monterrey fue Frank ___", "GONZÁLEZ", "PREGUNTA"],
    ["¿Qué animal es la mascota del Tec de Monterrey?", "BORREGO", "PREGUNTA"],
    ["Llevar el balón hasta la zona de anotación es un ___", "TOUCHDOWN", "PREGUNTA"],
    ["¿Cuántos puntos vale un touchdown?", "SEIS", "PREGUNTA"],
    ["¿Cuántos puntos vale un gol de campo?", "TRES", "PREGUNTA"],
    ["¿Cuántos puntos vale un safety?", "DOS", "PREGUNTA"],
    ["Después de un touchdown se patea para ganar el punto ___", "EXTRA", "PREGUNTA"],
    ["El jugador que lanza los pases es el mariscal de ___", "CAMPO", "PREGUNTA"],
    ["¿Cuántos jugadores tiene cada equipo en la cancha?", "ONCE", "PREGUNTA"],
    ["¿En cuántas oportunidades hay que avanzar diez yardas?", "CUATRO", "PREGUNTA"],
    ["La gran final de la NFL se llama el Super ___", "BOWL", "PREGUNTA"]
  ]
};
